GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxhbmlha2VhIiwiaWQiOiI2MmQ2MmExNDkzMTJhMzM3NDE4MTg0NTciLCJpYXQiOjE2NTgyMDI3MDMsImV4cCI6MTY1ODIwNjMwM30.3477q6L9Kkk1IJyqFuBY5bZyppgtV_PjzFny81Kn9ao

{
  "title": "Javascript for Dummies",
  "author": "Dunno",
  "url": "http://javascriptfordummies.org",
  "likes": 0
}

###

GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "laniakea",
  "password": "laniakea1",
  "name": "Lania Kea"
}

###

DELETE http://localhost:3003/api/blogs/61bd16901e9eab9d77841d0f
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxhbmlha2VhIiwiaWQiOiI2MmQ2MmExNDkzMTJhMzM3NDE4MTg0NTciLCJpYXQiOjE2NTgyMDI3MDMsImV4cCI6MTY1ODIwNjMwM30.3477q6L9Kkk1IJyqFuBY5bZyppgtV_PjzFny81Kn9ao