GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxhbmlha2VhIiwiaWQiOiI2MmQ2MmExNDkzMTJhMzM3NDE4MTg0NTciLCJpYXQiOjE2NTgyMDI3MDMsImV4cCI6MTY1ODIwNjMwM30.3477q6L9Kkk1IJyqFuBY5bZyppgtV_PjzFny81Kn9ao

{
  "title": "Javascript for Dummies",
  "author": "Dunno",
  "url": "http://javascriptfordummies.org",
  "likes": 0
}

###

POST http://localhost:3003/api/blogs/62d62c079312a33741818461/comments
Content-Type: application/json

{
  "comment": "+10 ty!"
}

###

GET http://localhost:3003/api/users

###

GET http://localhost:3003/api/users/62d62a149312a33741818457

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "bismuth",
  "password": "bismuth1",
  "name": "Bis Muth"
}

###

DELETE http://localhost:3003/api/blogs/61bd16901e9eab9d77841d0f
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxhbmlha2VhIiwiaWQiOiI2MmQ2MmExNDkzMTJhMzM3NDE4MTg0NTciLCJpYXQiOjE2NTgyMDI3MDMsImV4cCI6MTY1ODIwNjMwM30.3477q6L9Kkk1IJyqFuBY5bZyppgtV_PjzFny81Kn9ao