GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZXJ0eSIsImlkIjoiNjFiYjg1YzM2NDhmMWE4N2E0OGRlMTBhIiwiaWF0IjoxNjM5Nzg2NTU0LCJleHAiOjE2Mzk3OTAxNTR9.AmnFcE-E1Sd-RtEUAxjfN2oh7zPcaD2gxpB4eiIwqH0

{
  "title": "Javascript for Dummies",
  "author": "Dunno",
  "url": "http://javascriptfordummies.org",
  "likes": 0
}

###

GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "johndoe",
  "password": "pass1",
  "name": "John Doe"
}

###

DELETE http://localhost:3003/api/blogs/61bd16901e9eab9d77841d0f
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZXJ0eSIsImlkIjoiNjFiYjg1YzM2NDhmMWE4N2E0OGRlMTBhIiwiaWF0IjoxNjM5NzgxOTczLCJleHAiOjE2Mzk3ODU1NzN9.2x1BF1tj8XuzCr2wfPgBaBLTcm2rE_Kp5JUl3F55cLs